### ISSUE TITLE
Editor from entity management is added to menu 

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-frontend#483] opened 2021-07-02 07:12 UTC
**Enviroment:**
Ubuntu 20.04 LTS
Jmix version: 1.0.0
Jmix Studio plugin version: 1.0.0-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Ultimate Edition)

**TC:**
1. Create new project
2. Add frontend module
3. Create new frontend component `entity management` fo User entity
4. Open AppMenu.tsx

**AR:**
Two menu item are added:
```
<MenuItem
  screenId={"UserEditor"}
  icon={<BarsOutlined />}
  caption={"screen.UserEditor"}
  key={"638d3f96-0f26-4448-9682-579450c73bd2"}
/>
<MenuItem
  screenId={"UserList"}
  icon={<BarsOutlined />}
  caption={"screen.UserList"}
  key={"1dc1e93e-330a-4491-86e8-e5c86150c8ea"}
/>
```

**ER:**
only `entityList` component is added to menu

**Comment by web-devel** [comment] 2021-07-05 09:57
Duplicate of #479

**Closed by web-devel** 2021-07-05 09:57 UTC
